heroes:
- name: Abaddon
  excluded: false
  primary_attribute: Universal
  attack_type: Melee
- name: Alchemist
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Ancient Apparition
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Anti-Mage
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Arc Warden
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Axe
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Bane
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Batrider
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Beastmaster
  excluded: false
  primary_attribute: Universal
  attack_type: Melee
- name: Bloodseeker
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Bounty Hunter
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Brewmaster
  excluded: false
  primary_attribute: Universal
  attack_type: Melee
- name: Bristleback
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Broodmother
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Centaur Warrunner
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Chaos Knight
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Chen
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Clinkz
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Clockwerk
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Crystal Maiden
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Dark Seer
  excluded: false
  primary_attribute: Intelligence
  attack_type: Melee
- name: Dark Willow
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Dawnbreaker
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Dazzle
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Death Prophet
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Disruptor
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Doom
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Dragon Knight
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Drow Ranger
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Earth Spirit
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Earthshaker
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Elder Titan
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Ember Spirit
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Enchantress
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Enigma
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Faceless Void
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Grimstroke
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Gyrocopter
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Hoodwink
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Huskar
  excluded: false
  primary_attribute: Strength
  attack_type: Ranged
- name: Invoker
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Io
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Jakiro
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Juggernaut
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Keeper of the Light
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Kez
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Kunkka
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Largo
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Legion Commander
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Leshrac
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Lich
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Lifestealer
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Lina
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Lion
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Lone Druid
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Luna
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Lycan
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Magnus
  excluded: false
  primary_attribute: Universal
  attack_type: Melee
- name: Marci
  excluded: false
  primary_attribute: Universal
  attack_type: Melee
- name: Mars
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Medusa
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Meepo
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Mirana
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Monkey King
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Morphling
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Muerta
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Naga Siren
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Nature's Prophet
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Necrophos
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Night Stalker
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Nyx Assassin
  excluded: false
  primary_attribute: Universal
  attack_type: Melee
- name: Ogre Magi
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Omniknight
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Oracle
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Outworld Destroyer
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Pangolier
  excluded: false
  primary_attribute: Universal
  attack_type: Melee
- name: Phantom Assassin
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Phantom Lancer
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Phoenix
  excluded: false
  primary_attribute: Strength
  attack_type: Ranged
- name: Primal Beast
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Puck
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Pudge
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Pugna
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Queen of Pain
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Razor
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Riki
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Ringmaster
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Rubick
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Sand King
  excluded: false
  primary_attribute: Universal
  attack_type: Melee
- name: Shadow Demon
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Shadow Fiend
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Shadow Shaman
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Silencer
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Skywrath Mage
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Slardar
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Slark
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Snapfire
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Sniper
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Spectre
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Spirit Breaker
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Storm Spirit
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Sven
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Techies
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Templar Assassin
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Terrorblade
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Tidehunter
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Timbersaw
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Tinker
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Tiny
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Treant Protector
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Troll Warlord
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Tusk
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Underlord
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Undying
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Ursa
  excluded: false
  primary_attribute: Agility
  attack_type: Melee
- name: Vengeful Spirit
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Venomancer
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Viper
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Visage
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Void Spirit
  excluded: false
  primary_attribute: Universal
  attack_type: Melee
- name: Warlock
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Weaver
  excluded: false
  primary_attribute: Agility
  attack_type: Ranged
- name: Windranger
  excluded: false
  primary_attribute: Universal
  attack_type: Ranged
- name: Winter Wyvern
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Witch Doctor
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
- name: Wraith King
  excluded: false
  primary_attribute: Strength
  attack_type: Melee
- name: Zeus
  excluded: false
  primary_attribute: Intelligence
  attack_type: Ranged
