structure: Animist
memes:
- Proselytizer
- Darkness
- Cannibal
precepts:
  Fungus: Despised
  Male Clothing: Fully covered
  Diversity of thought: Moderate bigotry
  Women's spouses: Three or fewer
  Body modification: Disapproved
  Drug use: Medical only
  Execution: Respected if guilty
  Female Clothing: Pants at most
  Void study: Very efficient
  Scarification: Horrible
  Raiding: Respected
  Marriage Name: Random
  Organ use: Acceptable
  Skullspike: Desired
  Eating nutrient paste: Disgusting
  Physical Love: Free and approved
  Trees: Desired
  Research: Normal
  Men's spouses: Two or fewer
  Corpses: Ugly
  Killing innocent animals: Disapproved
  Cannibalism: Required (strong)
  Mechanoid labor: Enhanced
  Child labor: Disapproved
  Blindness: Horrible
  Charity: Important
  Slavery: Horrible
  Insect Meat: Despised
  Psychic rituals: Exalted
